// MAKE A BANGER — the reference parts a banger's faders are matched against, read out of
// songs. 2 Oct 2026.
//
// Shared by tools/banger-levels.js (`refs`, `check`) and tools/lib/banger-seeds.js (Use as
// Style, Save as Combo). What a reference is, and why, is at the top of
// tools/lib/banger/levels.js: the part a channel's settings were set for, with that
// channel's fader and widener — a seed remix's channel, a seed banger's, a combo's, or the
// style's own default part where nobody has set it by ear.
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { deskBank } from '../../src/engine/lanes.js';
import { VOICES, PERCUSSION_LANES } from '../../src/data/voices.js';
import { draftOf } from './arrangement-edit.js';
import { extractRiff } from './banger/riff.js';
import { generateBanger } from './banger/index.js';
import { BANGER_STYLES } from './banger/styles/index.js';
import { BIG_ROOM } from './banger/styles/big-room.js';
import { ROLE_ORDER } from './banger/lanes.js';
import { levelWindow, libraryCurveId, copyCurveKey, widenerOf, LEVEL_WINDOW_BARS } from './banger/levels.js';
import { L, P, hasNotes } from './banger/theory.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
export const LEVEL_DATA_FILE = 'tools/lib/banger/levels-data.js';
export const CHANNELS_FILE = 'tools/lib/banger/channels.js';

// Every job a banger channel can do, in the desk's order. The riser is song-local noise
// with nothing to match it against.
export const JOBS = ['hook', ...ROLE_ORDER].filter((j) => j !== 'riser');

const fresh = (root, rel) => import(`${pathToFileURL(join(root, rel)).href}?v=${Date.now()}`);
const isDrumLane = (lane) => PERCUSSION_LANES.includes(lane.replace(/\d+$/, ''));

// ---------------------------------------------------------------- the data file
export async function readLevelData(root = ROOT) {
  return structuredClone((await fresh(root, LEVEL_DATA_FILE)).BANGER_LEVEL_DATA);
}

export function levelDataSource(d) {
  const out = [
    '// MAKE A BANGER — what the levels are predicted from. GENERATED by tools/banger-levels.js;',
    '// do not edit by hand. See tools/lib/banger/levels.js for what each part means.',
    '//',
    '//   curves   per preset: how loud one note is (dB, at unity, dry) at three lengths and',
    '//            four pitches — `node tools/banger-levels.js curves`',
    '//   refs     per style, per job: the part its channel settings were set for — `refs`',
    '//   offsets  per style, per job: the average miss a check found — `check --fit`',
    'export const BANGER_LEVEL_DATA = {',
    `  version: ${d.version},`,
    '  curves: {',
    ...Object.keys(d.curves).sort().map((id) => `    ${JSON.stringify(id)}: ${JSON.stringify(d.curves[id])},`),
    '  },',
    '  refs: {',
  ];
  for (const st of Object.keys(d.refs)) {
    out.push(`    ${JSON.stringify(st)}: {`);
    for (const job of Object.keys(d.refs[st])) out.push(`      ${JSON.stringify(job)}: ${JSON.stringify(d.refs[st][job])},`);
    out.push('    },');
  }
  out.push('  },', '  offsets: {');
  for (const st of Object.keys(d.offsets)) out.push(`    ${JSON.stringify(st)}: ${JSON.stringify(d.offsets[st])},`);
  out.push('  },', '};', '');
  return out.join('\n');
}
export const writeLevelData = (root, d) => writeFileSync(join(root, LEVEL_DATA_FILE), levelDataSource(d));

// ---------------------------------------------------------------- songs and parts
/** A song as the desk plays it: bank, draft, mix, arrangement, tempo. */
export function songFrom(mod, id) {
  const bank = deskBank(mod.bank, mod.mix || null);
  const draft = draftOf(bank, mod.arrangement || null);
  return {
    id, title: mod.title || id, raw: mod, bank, draft, mix: mod.mix || {}, arrangement: mod.arrangement || null,
    bpm: draft.bpm ?? bank.bpm, bars: draft.plan.length,
  };
}

/** A song in a song folder, read fresh from disk — a seed somebody saved a moment ago is the one meant. */
export async function songAt(root, dir, id) {
  return songFrom(await fresh(root, `${dir}/${id}.js`), id);
}

/** One lane's part over bars `from`–`to` (0-based, inclusive), or null when it plays nothing there. */
export function lanePart(song, lane, from, to) {
  const riff = extractRiff({ bank: song.bank, draft: song.draft, mix: song.mix, from, to, laneKeys: [lane] });
  return riff.parts[0] || null;
}
const onsets = (s, drum) => (s == null ? 0 : drum ? P(s).filter(Boolean).length : L(s).notes.filter((v) => v != null).length);

/** The sound a part plays, as levels-data keeps it: a library id, or a song copy's numbers and the preset it was copied from. */
export function voiceRecord(part) {
  const p = part.voiceParams;
  if (p) {
    return {
      level: p.level ?? 0, peak: p.peak ?? 0, dur: p.dur ?? null, trim: p.trim ?? 0, label: p.label || null,
      copyOf: p.id || null, unedited: !!libraryCurveId(p), copyKey: copyCurveKey(p),
    };
  }
  if (part.voice) return { id: part.voice, label: VOICES[part.voice]?.label || part.voice };
  return { label: 'engine' };
}

// ---------------------------------------------------------------- the references
/** A seed remix channel's part for `job`: in the style's declared bars, or its busiest eight if it rests there. */
export function seedRef(seed, decl, job) {
  const lane = decl.lanes[job];
  const drum = isDrumLane(lane);
  let [a, b] = [decl.bars[0] - 1, decl.bars[1] - 1];
  let part = lanePart(seed, lane, a, b);
  if (!part) {
    const whole = lanePart(seed, lane, 0, seed.bars - 1);
    if (!whole) return null;
    let best = 0;
    for (let s = 0; s + LEVEL_WINDOW_BARS <= whole.bars.length; s++) {
      const n = whole.bars.slice(s, s + LEVEL_WINDOW_BARS).reduce((t, x) => t + onsets(x, drum), 0);
      if (n > best) { best = n; a = s; }
    }
    b = a + LEVEL_WINDOW_BARS - 1;
    part = { ...whole, bars: whole.bars.slice(a, b + 1) };
  }
  const label = seed.mix.labels?.[lane] || lane;
  return {
    from: `${seed.title} · ${label}, bars ${a + 1}–${b + 1}`, song: seed.id, window: [a, b], lane, bpm: seed.bpm,
    gain: seed.mix.lanes?.[lane]?.gain ?? 0, widener: widenerOf(seed.mix.lanes?.[lane]), voice: voiceRecord(part), bars: part.bars,
  };
}

/**
 * Every job's part in a banger, read where levels.js reads a banger's own — the first eight
 * bars it plays in its last drop. `laneOf` and `form` are the banger's (its recipe keeps
 * both). With `faders`, each reference carries the banger's own fader: what somebody set by
 * ear on a seed banger or a combo. Without, the style's recipe decides (a default part).
 * `tag` is merged into every reference (`{ song }`, `{ style, variant }`).
 */
export function bangerRefs(song, { laneOf, form, label, faders = true, tag = {}, refs = {} }) {
  for (const [job, lane] of Object.entries(laneOf)) {
    if (!JOBS.includes(job) || refs[job]) continue;
    const whole = lanePart(song, lane, 0, song.bars - 1);
    if (!whole) continue;
    const parsed = whole.bars.map((s) => (isDrumLane(lane) ? P(s) : L(s)));
    const w = levelWindow(form, (bar) => hasNotes(parsed[bar]));
    if (!w) continue;
    const sound = VOICES[whole.voice]?.label || whole.voiceParams?.label || whole.voice || 'its own voice';
    refs[job] = {
      from: `${label} · ${job} · ${sound}, bars ${w[0] + 1}–${w[1] + 1}`,
      ...tag, window: w, lane, bpm: song.bpm,
      gain: faders ? (song.mix.lanes?.[lane]?.gain ?? 0) : null, widener: widenerOf(song.mix.lanes?.[lane]),
      voice: voiceRecord(whole), bars: whole.bars.slice(w[0], w[1] + 1),
    };
  }
  return refs;
}

// The riffs a style's own default bangers are made from, for a channel set by hand that has
// no seed part. ABSOLUTE ZERO's one-bar hook on its own Electric Grand first; then the same
// notes spaced out, with piano chords, so the jobs the first never plays — a counter-line
// in the hook's rests, piano stabs — have a part too.
const riffOf = (bar) => ({
  version: 1, source: { id: 'levels-reference', title: 'REFERENCE', from: 0, to: 0, bpm: 128 }, bars: 1, grid: 16, stats: {},
  parts: [{
    key: 'lead', label: 'Grand', kind: 'melodic', role: 'hook', meanPitch: 74, voice: 'mrdrElectricGrand',
    voiceParams: null, engineKeys: null, strip: null, bars: [bar],
  }],
});
const DEFAULTS = [
  { riff: riffOf('D5:2 . F5:2 . A5:2 . F5:2 . D5:3 . . . C5:2 . E5:2 .'), parts: {} },
  { riff: riffOf('D5:2 . . . F5:2 . . . A5:2 . . . E5:2 . . .'), parts: { chords: 'piano' } },
];
// Every optional part on, so every job has a part to be read from.
const refOptions = (style, parts) => ({
  style: style.id, parts: { sub: true, thirdBelow: true, counter: true, ...parts },
  drums: { shaker: true, tambourine: true, congas: true, cowbell: true, ride: true },
});

/** The style's own default banger number `n`, unlevelled and on the recipe's own channels, as a song. */
export function defaultBanger(style, n = 0) {
  const { riff, parts } = DEFAULTS[n];
  const out = generateBanger({ riff, options: refOptions(style, parts), seed: 1, level: false, channels: {}, combos: {} });
  const song = songFrom({ bank: out.bank, mix: out.mix, arrangement: out.arrangement, title: `${style.label} default` }, `levels-${style.id}-${n}`);
  return { out, song };
}

/**
 * The reference for every job of every style. A style tuned from its seed banger (Use as
 * Style — channels.js names the seed) is matched to that seed banger, job for job. Anything
 * it has no part for falls back as before: the style's seed remix where the recipe copied
 * that channel from one, big-room's where it inherited big-room's channel, or the style's
 * own default part. `channels` is channels.js's table; `log(style, job, why, ref)` reports.
 */
export async function buildAllRefs(root = ROOT, { channels = {}, log = () => {} } = {}) {
  const styles = [BIG_ROOM, ...BANGER_STYLES.filter((s) => s.id !== BIG_ROOM.id)];
  const refs = {};
  for (const style of styles) {
    const tuned = channels[style.id]?.seed ? await songAt(root, 'src/data/imported', channels[style.id].seed).catch(() => null) : null;
    const fromSeed = tuned?.raw?.banger
      ? bangerRefs(tuned, { laneOf: tuned.raw.banger.laneOf || {}, form: tuned.raw.banger.form || [], label: tuned.title, tag: { song: tuned.id } })
      : {};
    const remix = style.seed ? await songAt(root, 'src/data/imported', style.seed.song).catch(() => null) : null;
    const own = {};
    for (let n = 0; n < DEFAULTS.length; n++) {
      const d = defaultBanger(style, n);
      bangerRefs(d.song, { laneOf: d.out.laneOf, form: d.out.form, label: `${style.label}'s own`, faders: false, tag: { style: style.id, variant: n }, refs: own });
    }
    refs[style.id] = {};
    for (const job of JOBS) {
      let ref = null; let why;
      if (fromSeed[job]) { ref = fromSeed[job]; why = 'seed banger'; }
      if (!ref && remix && style.seed.lanes[job]) { ref = seedRef(remix, style.seed, job); why = 'seed remix'; }
      if (!ref && style.id !== BIG_ROOM.id && style.strips[job] && style.strips[job] === BIG_ROOM.strips[job] && refs[BIG_ROOM.id][job]) {
        ref = refs[BIG_ROOM.id][job]; why = 'big-room\'s';
      }
      if (!ref && own[job]) { ref = own[job]; why = 'its own'; }
      if (!ref) continue;
      refs[style.id][job] = ref;
      log(style, job, why, ref);
    }
  }
  return refs;
}

/** The default bangers' songs, for the check to render a default reference in. */
export const defaultBangerSong = (style, n) => defaultBanger(style, n).song;
