// Writes src/data/songs/index.js — the folder's registry.
//
// Generated rather than hand-kept, for the same reason src/data/imported/index.js
// is: adding a song should be dropping a file in the folder, not remembering to
// mention it in three places. Rebuilt whenever the desk saves and by
// `node tools/migrate-songs.js --reindex`.
import { readdirSync, writeFileSync } from 'fs';
import { join } from 'path';

const SKIP = new Set(['index.js', 'shared.js']);

/** Every song file in the folder, in id order. */
export function songIds(dir) {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.js') && !SKIP.has(f))
    .map((f) => f.replace(/\.js$/, ''))
    .sort();
}

const varName = (id) => id.toUpperCase().replace(/[^A-Z0-9]+/g, '_');

export function writeSongsIndex(dir) {
  const ids = songIds(dir);
  const imports = ids.map((id) => `import * as ${varName(id)} from './${id}.js';`).join('\n');
  const entries = ids.map((id) => `  ${JSON.stringify(id)}: ${varName(id)},`).join('\n');

  const src = `// Every song in the game — GENERATED by tools/lib/songs-index.js. Do not edit.
//
// One file per song in this folder, each exporting \`bank\` (what it plays),
// \`arrangement\` (in what order) and \`mix\` (how it sounds). This module is only the
// list; the files themselves are ordinary source and are yours to edit above the
// line each one marks.
${imports}

export const SONGS = {
${entries}
};

/** Every song's id, in the order the folder holds them. */
export const SONG_IDS = Object.keys(SONGS);

/** \`{ id: mix }\` for the songs that carry one — what src/data/mix.js used to be. */
export const MIX_BY_ID = Object.fromEntries(
  Object.entries(SONGS).filter(([, s]) => s.mix).map(([id, s]) => [id, s.mix]),
);

/** \`{ id: arrangement }\` for the songs that carry one. */
// Keep nulls in this private index. They distinguish a song that was explicitly
// reset from a song whose file predates the migration; the compatibility export
// filters them when presenting the game's arrangement table.
export const ARRANGEMENT_BY_ID = Object.fromEntries(
  Object.entries(SONGS).map(([id, s]) => [id, s.arrangement ?? null]),
);

/** \`{ id: variants }\` for the songs that carry alternate presentations of themselves. */
// A variant is the same composition heard another way — the cabinet screen's treatment
// of a level's theme, so far. Filtered like MIX_BY_ID rather than kept with nulls,
// because "this song has no other presentation" is the ordinary case and every song
// would otherwise carry an entry saying nothing.
export const VARIANTS_BY_ID = Object.fromEntries(
  Object.entries(SONGS).filter(([, s]) => s.variants).map(([id, s]) => [id, s.variants]),
);
`;
  writeFileSync(join(dir, 'index.js'), src);
  return ids;
}
