// MAKE A BANGER — each style's channels, as its seed banger has them. GENERATED by Use as
// Style (tools/lib/banger-seeds.js); do not edit by hand. A style with no entry here plays
// its recipe's own channels (tools/lib/banger/styles/<style>.js); one with an entry plays
// these over them, job by job:
//
//   strips   per job: fader, pan, EQ, sends, inserts, note FX — as the seed's channel had them
//   sectionFx part Spot FX, positioned relative to the seed's musical sections
//   master   the master fader, its chain and the reverb/delay returns
//   pump     the chords' gate (the Sidechain Pump switch), taken off the chords channel
//   exciter  the hook's exciter (the moods that use one), taken off the hook channel
export const BANGER_CHANNELS = {
  "future-bass": {
    "seed": "banger-seed-future-bass",
    "at": "2026-10-04T05:00:18.114Z",
    "strips": {
      "hook": {
        "gain": -4.8,
        "pan": -0.05,
        "send": {
          "delay": 0.12,
          "reverb": 0.3
        }
      },
      "kick": {
        "gain": 0.5,
        "eq": {
          "low": -3
        }
      },
      "snare": {
        "gain": 3.7,
        "send": {
          "reverb": 0.3
        },
        "eq": {
          "low": 2.8,
          "high": 5.2
        }
      },
      "clap": {
        "gain": -1,
        "pan": -0.05,
        "send": {
          "reverb": 0.45
        }
      },
      "hats": {
        "gain": -1,
        "pan": 0.2
      },
      "ohats": {
        "gain": -8.1,
        "pan": -0.15
      },
      "crash": {
        "gain": -12.3,
        "pan": 0.2,
        "send": {
          "reverb": 0.9
        }
      },
      "riser": {
        "gain": -15.5,
        "send": {
          "reverb": 0.8
        },
        "eq": {
          "low": 5.5,
          "high": 2
        }
      },
      "impact": {
        "gain": -4.96,
        "send": {
          "reverb": 0.6
        }
      },
      "fill": {
        "gain": -5,
        "pan": 0.2,
        "send": {
          "reverb": 0.3
        }
      },
      "shaker": {
        "gain": -15,
        "pan": 0.3
      },
      "tambourine": {
        "gain": -12,
        "pan": -0.3,
        "send": {
          "reverb": 0.15
        }
      },
      "cowbell": {
        "gain": -13,
        "pan": 0.25,
        "send": {
          "reverb": 0.15
        }
      },
      "congas": {
        "gain": -8,
        "pan": -0.2,
        "send": {
          "reverb": 0.15
        }
      },
      "ride": {
        "gain": -12,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "bass": {
        "gain": -14.6,
        "effects": [
          {
            "id": "distortion",
            "params": {
              "distortion": 0.3,
              "wet": 0.45
            }
          }
        ]
      },
      "sub": {
        "gain": -5.68,
        "effects": [
          {
            "id": "filter",
            "params": {
              "type": "lowpass",
              "frequency": 5000,
              "Q": 0.7
            }
          }
        ]
      },
      "saws": {
        "gain": -13.1,
        "send": {
          "reverb": 1.25
        },
        "eq": {
          "low": -1,
          "high": 4
        },
        "effects": [
          {
            "id": "peq",
            "params": {
              "f2": 450,
              "g2": -2,
              "q2": 0.9
            }
          },
          {
            "id": "widener"
          }
        ]
      },
      "piano": {
        "gain": 2.7,
        "send": {
          "delay": 0.15,
          "reverb": 0.45
        }
      },
      "pad": {
        "gain": -16.5,
        "send": {
          "reverb": 0.5
        },
        "eq": {
          "high": 2
        }
      },
      "square": {
        "gain": -13.7,
        "send": {
          "delay": 0.2,
          "reverb": 0.35
        },
        "eq": {
          "mid": -2,
          "high": 2
        }
      },
      "bell": {
        "gain": -6.16,
        "pan": 0.15,
        "send": {
          "delay": 0.25,
          "reverb": 0.4
        },
        "eq": {
          "high": 3
        }
      },
      "megaSaw": {
        "gain": -9.68,
        "send": {
          "reverb": 0.25
        },
        "eq": {
          "low": -3
        }
      },
      "arp": {
        "gain": -11.4,
        "pan": -0.25,
        "send": {
          "delay": 0.2,
          "reverb": 0.2
        },
        "effects": [
          {
            "id": "autopanner",
            "params": {
              "rateSync": 1,
              "rateDivision": 2,
              "depth": 0.5,
              "wet": 1
            }
          }
        ]
      },
      "choir": {
        "gain": -15,
        "send": {
          "reverb": 0.679
        },
        "effects": [
          {
            "id": "widener",
            "params": {
              "width": 0.9
            }
          }
        ]
      },
      "third": {
        "gain": -5.4,
        "pan": 0.15,
        "send": {
          "delay": 0.1,
          "reverb": 0.3
        }
      },
      "counter": {
        "gain": -8.7,
        "pan": -0.2,
        "send": {
          "delay": 0.2,
          "reverb": 0.3
        }
      }
    },
    "master": {
      "master": 0,
      "masterEffects": [
        {
          "id": "mbCompN",
          "params": {
            "lowFrequency": 180,
            "highFrequency": 1800,
            "low.threshold": -26,
            "low.ratio": 4,
            "low.attack": 0.06,
            "low.release": 0.22,
            "low.knee": 8,
            "mid.threshold": -22,
            "mid.ratio": 3.5,
            "mid.attack": 0.018,
            "mid.release": 0.08,
            "mid.knee": 12,
            "high.threshold": -26,
            "high.ratio": 2.5,
            "high.attack": 0.01,
            "high.release": 0.06,
            "high.knee": 10
          }
        },
        {
          "id": "gain",
          "params": {
            "gain": -5.8
          }
        }
      ],
      "fx": {
        "reverb": {
          "decay": 3.2
        }
      }
    },
    "pump": {
      "id": "rhythmgate",
      "params": {
        "division": 0.5,
        "gateLength": 0.6,
        "attack": 0.004,
        "decay": 0.06,
        "depth": 0.85
      }
    },
    "exciter": {
      "id": "exciter",
      "params": {
        "tune": 2500,
        "drive": 0.5,
        "timbre": 0.4,
        "mix": 0.18
      }
    },
    "sectionFx": {
      "version": 1,
      "rules": [
        {
          "role": "hook",
          "section": "intro",
          "occurrence": 0,
          "occurrences": 1,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 200,
                "Q": 1.2,
                "sweep": 1,
                "sweepTo": 18000
              }
            },
            {
              "id": "widener",
              "params": {
                "width": 0.7,
                "sweep": 0,
                "widthTo": 0.7
              }
            }
          ],
          "sourceSection": "intro",
          "sourceIndex": 0
        },
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 0,
          "occurrences": 3,
          "from": 0.984375,
          "to": 1,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "drop",
          "sourceIndex": 2
        },
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 1,
          "occurrences": 3,
          "from": 0.9375,
          "to": 0.96875,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "drop2",
          "sourceIndex": 5
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "saws",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "saws",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "piano",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "piano",
          "section": "breakdown",
          "occurrence": 0,
          "occurrences": 1,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "pingpong",
              "params": {
                "sync": 1,
                "division": 0.5,
                "delayMs": 250,
                "feedback": 0.3,
                "wet": 0.35,
                "sweep": 0,
                "feedbackTo": 0.3,
                "wetTo": 0.35
              }
            },
            {
              "id": "gain",
              "params": {
                "gain": -2
              }
            }
          ],
          "sourceSection": "breakdown",
          "sourceIndex": 3
        },
        {
          "role": "piano",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        }
      ]
    }
  },
  "big-room": {
    "seed": "banger-seed-big-room",
    "at": "2026-10-06T01:35:46.152Z",
    "strips": {
      "hook": {
        "pan": -0.05,
        "send": {
          "delay": 0.12,
          "reverb": 0.3
        }
      },
      "kick": {
        "gain": 0.5,
        "eq": {
          "low": -3
        }
      },
      "snare": {
        "gain": 4,
        "send": {
          "reverb": 0.25
        },
        "eq": {
          "low": 2.8,
          "high": 5.2
        }
      },
      "clap": {
        "pan": 0.05,
        "send": {
          "reverb": 0.35
        },
        "eq": {
          "high": -1.5
        }
      },
      "hats": {
        "gain": -4.9,
        "pan": 0.2
      },
      "ohats": {
        "gain": -9,
        "pan": -0.15
      },
      "crash": {
        "gain": -2.9,
        "pan": 0.2,
        "send": {
          "reverb": 1.607
        },
        "eq": {
          "low": -3.1,
          "high": 0.7
        }
      },
      "riser": {
        "gain": -15.5,
        "send": {
          "reverb": 0.8
        },
        "eq": {
          "low": 5.5,
          "high": 2
        }
      },
      "impact": {
        "gain": -3,
        "send": {
          "reverb": 0.6
        }
      },
      "fill": {
        "gain": -5,
        "pan": 0.2,
        "send": {
          "reverb": 0.3
        }
      },
      "shaker": {
        "gain": -15,
        "pan": 0.3
      },
      "tambourine": {
        "gain": -12,
        "pan": -0.3,
        "send": {
          "reverb": 0.15
        }
      },
      "cowbell": {
        "gain": -13,
        "pan": 0.25,
        "send": {
          "reverb": 0.15
        }
      },
      "congas": {
        "gain": -8,
        "pan": -0.2,
        "send": {
          "reverb": 0.15
        }
      },
      "ride": {
        "gain": -12,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "bass": {
        "gain": -6.9,
        "effects": [
          {
            "id": "filter",
            "params": {
              "type": "lowpass",
              "frequency": 1400,
              "Q": 0.8
            }
          }
        ]
      },
      "sub": {
        "gain": -11.1
      },
      "saws": {
        "gain": -10.08,
        "send": {
          "reverb": 1.25
        },
        "eq": {
          "low": -3
        },
        "effects": [
          {
            "id": "peq",
            "params": {
              "f3": 3000,
              "g3": -2,
              "q3": 0.9
            }
          }
        ]
      },
      "pad": {
        "gain": -11.06,
        "send": {
          "reverb": 0.649
        },
        "eq": {
          "low": -4
        },
        "effects": [
          {
            "id": "widener",
            "params": {
              "width": 0.8
            }
          }
        ]
      },
      "square": {
        "gain": 1.1,
        "pan": 0.05,
        "send": {
          "delay": 0.1,
          "reverb": 0.2
        },
        "effects": [
          {
            "id": "peq",
            "params": {
              "f3": 3000,
              "g3": -2,
              "q3": 0.9
            }
          }
        ]
      },
      "bell": {
        "gain": -6.9,
        "pan": 0.2,
        "send": {
          "delay": 0.25,
          "reverb": 0.45
        }
      },
      "megaSaw": {
        "gain": -5.5,
        "send": {
          "reverb": 0.25
        },
        "eq": {
          "low": -3
        }
      },
      "arp": {
        "gain": -10.5,
        "pan": -0.25,
        "send": {
          "delay": 0.2,
          "reverb": 0.2
        },
        "effects": [
          {
            "id": "autopanner",
            "params": {
              "rateSync": 1,
              "rateDivision": 2,
              "depth": 0.5,
              "wet": 1
            }
          }
        ]
      },
      "choir": {
        "gain": -11.21,
        "send": {
          "reverb": 0.679
        },
        "effects": [
          {
            "id": "widener",
            "params": {
              "width": 0.9
            }
          }
        ]
      },
      "third": {
        "gain": -6.3,
        "pan": 0.15,
        "send": {
          "delay": 0.1,
          "reverb": 0.3
        }
      },
      "counter": {
        "gain": -8.3,
        "pan": -0.2,
        "send": {
          "delay": 0.2,
          "reverb": 0.3
        }
      }
    },
    "master": {
      "master": 0,
      "masterEffects": [
        {
          "id": "mbCompN",
          "params": {
            "lowFrequency": 180,
            "highFrequency": 1800,
            "low.threshold": -26,
            "low.ratio": 4,
            "low.attack": 0.06,
            "low.release": 0.22,
            "low.knee": 8,
            "mid.threshold": -22,
            "mid.ratio": 3.5,
            "mid.attack": 0.018,
            "mid.release": 0.08,
            "mid.knee": 12,
            "high.threshold": -26,
            "high.ratio": 2.5,
            "high.attack": 0.01,
            "high.release": 0.06,
            "high.knee": 10
          }
        },
        {
          "id": "gain",
          "params": {
            "gain": -5.8
          }
        }
      ],
      "fx": {
        "reverb": {
          "decay": 2.8
        }
      }
    },
    "pump": {
      "id": "rhythmgate",
      "params": {
        "division": 1,
        "gateLength": 1,
        "attack": 0.16,
        "decay": 0.02,
        "depth": 0.65
      }
    },
    "exciter": {
      "id": "exciter",
      "params": {
        "tune": 2500,
        "drive": 0.5,
        "timbre": 0.4,
        "mix": 0.18
      }
    },
    "sectionFx": {
      "version": 1,
      "rules": [
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 0,
          "occurrences": 3,
          "from": 0.984375,
          "to": 1,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "drop",
          "sourceIndex": 2
        },
        {
          "role": "hook",
          "section": "breakdown",
          "occurrence": 0,
          "occurrences": 1,
          "from": 0,
          "to": 0.875,
          "chain": [
            {
              "id": "pingpong",
              "params": {
                "sync": 1,
                "division": 0.5,
                "delayMs": 250,
                "feedback": 0.3,
                "wet": 0.35,
                "sweep": 0,
                "feedbackTo": 0.3,
                "wetTo": 0.35
              }
            }
          ],
          "sourceSection": "breakdown",
          "sourceIndex": 3
        },
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 1,
          "occurrences": 3,
          "from": 0.9375,
          "to": 0.96875,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "drop2",
          "sourceIndex": 5
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "saws",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "saws",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        }
      ]
    }
  },
  "reggaeton": {
    "seed": "banger-seed-reggaeton",
    "at": "2026-10-06T00:34:44.997Z",
    "strips": {
      "hook": {
        "gain": -5,
        "pan": -0.1,
        "send": {
          "delay": 0.2,
          "reverb": 0.25
        }
      },
      "kick": {},
      "snare": {
        "gain": -0.8,
        "send": {
          "reverb": 0.15
        },
        "eq": {
          "high": 3.7
        }
      },
      "clap": {
        "gain": 2.112,
        "send": {
          "delay": 0.004,
          "reverb": 0.197
        },
        "eq": {
          "low": -0.7,
          "mid": 0.6,
          "high": 3.7
        }
      },
      "hats": {
        "gain": 4.512,
        "pan": -0.15
      },
      "ohats": {
        "gain": -1.44,
        "pan": 0.15
      },
      "crash": {
        "gain": -3.68,
        "pan": 0.2,
        "send": {
          "reverb": 0.5
        }
      },
      "riser": {
        "gain": -15.5,
        "send": {
          "reverb": 0.8
        },
        "eq": {
          "low": 5.5,
          "high": 2
        }
      },
      "impact": {
        "gain": -14.5,
        "send": {
          "reverb": 0.6
        }
      },
      "fill": {
        "gain": -7,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "shaker": {
        "gain": -5.68,
        "pan": 0.3
      },
      "tambourine": {
        "gain": -6.08,
        "pan": -0.3,
        "send": {
          "reverb": 0.15
        }
      },
      "cowbell": {
        "gain": -7.44,
        "pan": 0.25,
        "send": {
          "reverb": 0.15
        }
      },
      "congas": {
        "gain": -11.1,
        "pan": 0.35,
        "send": {
          "reverb": 0.2
        }
      },
      "ride": {
        "gain": -1.12,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "bass": {
        "gain": -4.2,
        "effects": [
          {
            "id": "filter",
            "params": {
              "type": "lowpass",
              "frequency": 1200,
              "Q": 0.7
            }
          }
        ]
      },
      "sub": {
        "gain": -14
      },
      "piano": {
        "gain": -5.7,
        "pan": -0.2,
        "send": {
          "delay": 0.1,
          "reverb": 0.25
        },
        "eq": {
          "low": -3
        }
      },
      "pad": {
        "gain": -13.6,
        "send": {
          "reverb": 0.5
        },
        "eq": {
          "low": -6
        },
        "effects": [
          {
            "id": "filter",
            "params": {
              "type": "lowpass",
              "frequency": 3200,
              "Q": 0.7
            }
          }
        ]
      },
      "square": {
        "gain": 0.3,
        "pan": 0.05,
        "send": {
          "delay": 0.1,
          "reverb": 0.2
        },
        "effects": [
          {
            "id": "peq",
            "params": {
              "f3": 3000,
              "g3": -2,
              "q3": 0.9
            }
          }
        ]
      },
      "bell": {
        "gain": -11.9,
        "pan": 0.2,
        "send": {
          "delay": 0.25,
          "reverb": 0.45
        }
      },
      "megaSaw": {
        "gain": -14.2,
        "pan": 0.1,
        "send": {
          "reverb": 0.3
        }
      },
      "arp": {
        "gain": -14.3,
        "pan": 0.25,
        "send": {
          "delay": 0.25,
          "reverb": 0.3
        }
      },
      "choir": {
        "gain": -11,
        "send": {
          "reverb": 0.5
        }
      },
      "third": {
        "gain": -4.5,
        "pan": 0.15,
        "send": {
          "delay": 0.1,
          "reverb": 0.3
        }
      },
      "counter": {
        "gain": -7.8,
        "pan": 0.15,
        "send": {
          "delay": 0.35,
          "reverb": 0.5
        }
      }
    },
    "master": {
      "master": 0,
      "masterEffects": [
        {
          "id": "mbCompN",
          "params": {
            "lowFrequency": 180,
            "highFrequency": 1800,
            "low.threshold": -26,
            "low.ratio": 4,
            "low.attack": 0.06,
            "low.release": 0.22,
            "low.knee": 8,
            "mid.threshold": -22,
            "mid.ratio": 3.5,
            "mid.attack": 0.018,
            "mid.release": 0.08,
            "mid.knee": 12,
            "high.threshold": -26,
            "high.ratio": 2.5,
            "high.attack": 0.01,
            "high.release": 0.06,
            "high.knee": 10
          }
        },
        {
          "id": "gain",
          "params": {
            "gain": -5.8
          }
        }
      ],
      "fx": {
        "reverb": {
          "decay": 2.8
        }
      }
    },
    "pump": null,
    "exciter": null,
    "sectionFx": {
      "version": 1,
      "rules": [
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0.9895833333333334,
          "to": 1,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "Chorus",
          "sourceIndex": 2
        }
      ]
    }
  },
  "chipstep": {
    "seed": "banger-seed-chipstep",
    "at": "2026-10-05T10:56:41.550Z",
    "strips": {
      "hook": {
        "pan": -0.05,
        "send": {
          "delay": 0.12,
          "reverb": 0.3
        }
      },
      "kick": {
        "gain": 6
      },
      "snare": {
        "gain": 6,
        "send": {
          "reverb": 0.15
        }
      },
      "clap": {
        "send": {
          "reverb": 0.3
        }
      },
      "hats": {
        "gain": -0.72,
        "pan": 0.2
      },
      "ohats": {
        "gain": -3.12,
        "pan": -0.2
      },
      "crash": {
        "gain": -4.56,
        "pan": 0.3,
        "send": {
          "reverb": 0.3
        }
      },
      "riser": {
        "gain": -16.8,
        "send": {
          "reverb": 0.8
        },
        "eq": {
          "low": 5.5
        }
      },
      "impact": {
        "gain": -2,
        "send": {
          "reverb": 0.5
        },
        "effects": [
          {
            "id": "pingpong",
            "params": {
              "sync": 1,
              "division": 0.75,
              "feedback": 0.5,
              "wet": 0.45
            }
          }
        ]
      },
      "fill": {
        "gain": -4.1,
        "pan": 0.2,
        "send": {
          "reverb": 0.3
        }
      },
      "shaker": {
        "gain": -15,
        "pan": 0.3
      },
      "tambourine": {
        "gain": -12,
        "pan": -0.3,
        "send": {
          "reverb": 0.15
        }
      },
      "cowbell": {
        "gain": -13,
        "pan": 0.25,
        "send": {
          "reverb": 0.15
        }
      },
      "congas": {
        "gain": -8,
        "pan": -0.2,
        "send": {
          "reverb": 0.15
        }
      },
      "ride": {
        "gain": -12,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "bass": {
        "gain": -2.4
      },
      "sub": {
        "gain": -6.3
      },
      "saws": {
        "gain": -15.1,
        "send": {
          "reverb": 0.64
        },
        "effects": []
      },
      "pad": {
        "gain": -13.1,
        "send": {
          "reverb": 0.64
        }
      },
      "square": {
        "gain": -4.4,
        "send": {
          "delay": 0.15,
          "reverb": 0.2
        }
      },
      "bell": {
        "gain": -8.8,
        "pan": 0.2,
        "send": {
          "delay": 0.25,
          "reverb": 0.45
        }
      },
      "megaSaw": {
        "gain": -6.4,
        "pan": 0.25,
        "send": {
          "reverb": 0.3
        }
      },
      "arp": {
        "gain": -7,
        "pan": -0.3,
        "send": {
          "delay": 0.2
        },
        "effects": [
          {
            "id": "autopanner",
            "params": {
              "rateSync": 1,
              "rateDivision": 2,
              "depth": 0.6,
              "wet": 1
            }
          }
        ]
      },
      "choir": {
        "gain": -9.3,
        "send": {
          "reverb": 0.5
        }
      },
      "third": {
        "gain": -5,
        "pan": 0.2,
        "send": {
          "reverb": 0.3
        }
      },
      "counter": {
        "gain": -3.8,
        "pan": -0.2,
        "send": {
          "delay": 0.2,
          "reverb": 0.3
        }
      }
    },
    "master": {
      "master": 0,
      "masterEffects": [
        {
          "id": "mbCompN",
          "params": {
            "lowFrequency": 180,
            "highFrequency": 1800,
            "low.threshold": -26,
            "low.ratio": 4,
            "low.attack": 0.06,
            "low.release": 0.22,
            "low.knee": 8,
            "mid.threshold": -22,
            "mid.ratio": 3.5,
            "mid.attack": 0.018,
            "mid.release": 0.08,
            "mid.knee": 12,
            "high.threshold": -26,
            "high.ratio": 2.5,
            "high.attack": 0.01,
            "high.release": 0.06,
            "high.knee": 10
          }
        },
        {
          "id": "gain",
          "params": {
            "gain": -5
          }
        }
      ],
      "fx": {}
    },
    "pump": {
      "id": "rhythmgate",
      "params": {
        "division": 1,
        "gateLength": 1,
        "attack": 0.14,
        "decay": 0.02,
        "depth": 0.6
      }
    },
    "exciter": {
      "id": "exciter",
      "params": {
        "tune": 2500,
        "drive": 0.5,
        "timbre": 0.4,
        "mix": 0.18
      }
    },
    "sectionFx": {
      "version": 1,
      "rules": [
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 0,
          "occurrences": 3,
          "from": 0.984375,
          "to": 1,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "drop",
          "sourceIndex": 2
        },
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 1,
          "occurrences": 3,
          "from": 0.9375,
          "to": 0.96875,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "drop2",
          "sourceIndex": 5
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "saws",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "saws",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        }
      ]
    }
  },
  "trance": {
    "seed": "banger-seed-trance",
    "at": "2026-10-06T01:09:15.464Z",
    "strips": {
      "hook": {
        "pan": -0.05,
        "send": {
          "delay": 0.12,
          "reverb": 0.3
        }
      },
      "kick": {
        "gain": 0.5,
        "eq": {
          "low": -3
        }
      },
      "snare": {
        "gain": 4,
        "send": {
          "reverb": 0.25
        },
        "eq": {
          "low": 2.8,
          "high": 5.2
        }
      },
      "clap": {
        "gain": 1.056,
        "pan": 0.05,
        "send": {
          "reverb": 0.35
        }
      },
      "hats": {
        "gain": -3.6,
        "pan": -0.243,
        "eq": {
          "high": 1
        }
      },
      "ohats": {
        "gain": 1.5,
        "pan": -0.342
      },
      "crash": {
        "gain": 1.968,
        "pan": 0.497,
        "send": {
          "reverb": 0.9
        },
        "eq": {
          "high": 6.2
        }
      },
      "riser": {
        "gain": -9.84,
        "send": {
          "reverb": 0.8
        },
        "eq": {
          "low": 5.5,
          "high": 0.6
        },
        "effects": [
          {
            "id": "ambience"
          }
        ]
      },
      "impact": {
        "gain": -3,
        "send": {
          "reverb": 0.6
        }
      },
      "fill": {
        "gain": -5,
        "pan": 0.2,
        "send": {
          "reverb": 0.3
        }
      },
      "shaker": {
        "gain": -15,
        "pan": 0.3
      },
      "tambourine": {
        "gain": -12,
        "pan": -0.3,
        "send": {
          "reverb": 0.15
        }
      },
      "cowbell": {
        "gain": -10,
        "pan": 0.25,
        "send": {
          "reverb": 0.15
        }
      },
      "congas": {
        "gain": -8,
        "pan": -0.2,
        "send": {
          "reverb": 0.15
        }
      },
      "ride": {
        "gain": -12,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "bass": {
        "gain": -8,
        "effects": [
          {
            "id": "filter",
            "params": {
              "type": "lowpass",
              "frequency": 1800,
              "Q": 0.9
            }
          }
        ]
      },
      "sub": {
        "gain": -11
      },
      "saws": {
        "gain": -0.9,
        "send": {
          "delay": 0.12,
          "reverb": 0.35
        },
        "eq": {
          "low": -3
        },
        "effects": []
      },
      "piano": {
        "gain": -0.2,
        "send": {
          "delay": 0.18,
          "reverb": 0.55
        }
      },
      "pad": {
        "gain": -7.1,
        "send": {
          "reverb": 0.6
        },
        "eq": {
          "low": -4
        },
        "effects": [
          {
            "id": "doubler"
          }
        ]
      },
      "square": {
        "gain": -5,
        "pan": 0.05,
        "send": {
          "delay": 0.1,
          "reverb": 0.2
        },
        "effects": [
          {
            "id": "peq",
            "params": {
              "f3": 3000,
              "g3": -2,
              "q3": 0.9
            }
          }
        ]
      },
      "bell": {
        "gain": -7.3,
        "pan": 0.2,
        "send": {
          "delay": 0.25,
          "reverb": 0.45
        }
      },
      "megaSaw": {
        "gain": -5.6,
        "send": {
          "reverb": 0.25
        },
        "eq": {
          "low": -3
        }
      },
      "arp": {
        "gain": -9,
        "pan": -0.2,
        "send": {
          "delay": 0.3,
          "reverb": 0.3
        },
        "effects": [
          {
            "id": "autopanner",
            "params": {
              "rateSync": 1,
              "rateDivision": 2,
              "depth": 0.5,
              "wet": 1
            }
          }
        ]
      },
      "choir": {
        "gain": -7.2,
        "send": {
          "reverb": 0.679
        },
        "eq": {
          "high": 1.2
        },
        "effects": [
          {
            "id": "widener",
            "bypass": true,
            "params": {
              "width": 0.9
            }
          },
          {
            "id": "doubler"
          }
        ]
      },
      "third": {
        "gain": -5.4,
        "pan": 0.15,
        "send": {
          "delay": 0.1,
          "reverb": 0.3
        }
      },
      "counter": {
        "gain": -8.3,
        "pan": -0.2,
        "send": {
          "delay": 0.2,
          "reverb": 0.3
        }
      }
    },
    "master": {
      "master": 0,
      "masterEffects": [
        {
          "id": "mbCompN",
          "params": {
            "lowFrequency": 180,
            "highFrequency": 1800,
            "low.threshold": -26,
            "low.ratio": 4,
            "low.attack": 0.06,
            "low.release": 0.22,
            "low.knee": 8,
            "mid.threshold": -22,
            "mid.ratio": 3.5,
            "mid.attack": 0.018,
            "mid.release": 0.08,
            "mid.knee": 12,
            "high.threshold": -26,
            "high.ratio": 2.5,
            "high.attack": 0.01,
            "high.release": 0.06,
            "high.knee": 10
          }
        },
        {
          "id": "gain",
          "params": {
            "gain": -5.8
          }
        }
      ],
      "fx": {
        "reverb": {
          "decay": 3.6
        }
      }
    },
    "pump": {
      "id": "rhythmgate",
      "params": {
        "division": 0.25,
        "gateLength": 0.61,
        "attack": 0.003,
        "decay": 0.04,
        "depth": 0.9
      }
    },
    "exciter": {
      "id": "exciter",
      "params": {
        "tune": 2500,
        "drive": 0.5,
        "timbre": 0.4,
        "mix": 0.18
      }
    },
    "sectionFx": {
      "version": 1,
      "rules": [
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 0,
          "occurrences": 3,
          "from": 0.9895833333333334,
          "to": 1,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "drop",
          "sourceIndex": 2
        },
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 1,
          "occurrences": 3,
          "from": 0.96875,
          "to": 0.984375,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "drop2",
          "sourceIndex": 5
        },
        {
          "role": "riser",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0.75,
          "to": 0.875,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 200,
                "Q": 1.2,
                "sweep": 1,
                "sweepTo": 18000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "saws",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "saws",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "piano",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "piano",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build",
          "sourceIndex": 1
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "build2",
          "sourceIndex": 4
        }
      ]
    }
  },
  "italo-disco": {
    "seed": "banger-seed-italo-disco",
    "at": "2026-10-06T01:12:50.378Z",
    "strips": {
      "hook": {
        "gain": -5,
        "pan": 0.05,
        "send": {
          "delay": 0.25,
          "reverb": 0.4
        }
      },
      "kick": {},
      "snare": {
        "gain": -3,
        "send": {
          "reverb": 0.35
        }
      },
      "clap": {
        "gain": 1.5,
        "send": {
          "reverb": 0.378
        },
        "eq": {
          "mid": 1.9,
          "high": 0.4
        }
      },
      "hats": {
        "gain": -0.3,
        "pan": -0.2
      },
      "ohats": {
        "gain": -10,
        "pan": 0.2
      },
      "crash": {
        "gain": -10,
        "pan": 0.2,
        "send": {
          "reverb": 0.5
        }
      },
      "fill": {
        "gain": -6,
        "pan": 0.15,
        "send": {
          "reverb": 0.3
        }
      },
      "shaker": {
        "gain": -12.6,
        "pan": 0.3
      },
      "tambourine": {
        "gain": -9.4,
        "pan": -0.3,
        "send": {
          "reverb": 0.15
        }
      },
      "cowbell": {
        "gain": -6.4,
        "pan": 0.25,
        "send": {
          "reverb": 0.15
        }
      },
      "congas": {
        "gain": -7.1,
        "pan": -0.2,
        "send": {
          "reverb": 0.15
        }
      },
      "ride": {
        "gain": -12,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "bass": {
        "gain": -5.2
      },
      "sub": {
        "gain": -16.1
      },
      "pad": {
        "gain": -5.9,
        "send": {
          "reverb": 0.5
        },
        "eq": {
          "low": -5
        }
      },
      "square": {
        "gain": -6.6,
        "pan": 0.05,
        "send": {
          "delay": 0.1,
          "reverb": 0.2
        },
        "effects": [
          {
            "id": "peq",
            "params": {
              "f3": 3000,
              "g3": -2,
              "q3": 0.9
            }
          }
        ]
      },
      "bell": {
        "gain": -9.1,
        "pan": 0.2,
        "send": {
          "delay": 0.25,
          "reverb": 0.45
        }
      },
      "megaSaw": {
        "gain": -12.2,
        "send": {
          "reverb": 0.35
        }
      },
      "arp": {
        "gain": -22.5,
        "pan": -0.25,
        "effects": [
          {
            "id": "pingpong",
            "params": {
              "sync": 1,
              "division": 0.75,
              "feedback": 0.35,
              "wet": 0.3
            }
          }
        ]
      },
      "choir": {
        "gain": -10,
        "send": {
          "reverb": 0.5
        }
      },
      "third": {
        "gain": -4.8,
        "pan": 0.15,
        "send": {
          "delay": 0.1,
          "reverb": 0.3
        }
      },
      "counter": {
        "gain": -8,
        "pan": -0.2,
        "send": {
          "delay": 0.2,
          "reverb": 0.3
        }
      }
    },
    "master": {
      "master": 0,
      "masterEffects": [
        {
          "id": "mbCompN",
          "params": {
            "lowFrequency": 180,
            "highFrequency": 1800,
            "low.threshold": -26,
            "low.ratio": 4,
            "low.attack": 0.06,
            "low.release": 0.22,
            "low.knee": 8,
            "mid.threshold": -22,
            "mid.ratio": 3.5,
            "mid.attack": 0.018,
            "mid.release": 0.08,
            "mid.knee": 12,
            "high.threshold": -26,
            "high.ratio": 2.5,
            "high.attack": 0.01,
            "high.release": 0.06,
            "high.knee": 10
          }
        },
        {
          "id": "gain",
          "params": {
            "gain": -5.8
          }
        }
      ],
      "fx": {
        "reverb": {
          "decay": 2.8
        }
      }
    },
    "pump": null,
    "exciter": null,
    "sectionFx": {
      "version": 1,
      "rules": [
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0.9895833333333334,
          "to": 1,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "Chorus",
          "sourceIndex": 2
        }
      ]
    }
  },
  "megadrive": {
    "seed": "banger-seed-megadrive",
    "at": "2026-10-06T01:39:25.692Z",
    "strips": {
      "hook": {
        "pan": -0.05,
        "send": {
          "delay": 0.12,
          "reverb": 0.3
        }
      },
      "kick": {
        "eq": {
          "low": -1
        }
      },
      "snare": {
        "gain": 0.24,
        "send": {
          "reverb": 0.15
        },
        "eq": {
          "mid": 1.6,
          "high": 2
        }
      },
      "clap": {
        "gain": 2.544,
        "send": {
          "reverb": 0.15
        },
        "eq": {
          "high": 1
        }
      },
      "hats": {
        "gain": -8,
        "pan": 0.2
      },
      "ohats": {
        "gain": -11,
        "pan": -0.15
      },
      "crash": {
        "gain": -7.6,
        "pan": 0.2,
        "send": {
          "delay": 0.408,
          "reverb": 0.541
        }
      },
      "fill": {
        "gain": -3,
        "pan": 0.2,
        "send": {
          "reverb": 0.15
        }
      },
      "shaker": {
        "gain": -12.6,
        "pan": 0.3
      },
      "tambourine": {
        "gain": -9.76,
        "pan": -0.3,
        "send": {
          "reverb": 0.15
        }
      },
      "cowbell": {
        "gain": -8.8,
        "pan": 0.25,
        "send": {
          "reverb": 0.15
        }
      },
      "congas": {
        "gain": -8,
        "pan": -0.2,
        "send": {
          "reverb": 0.15
        }
      },
      "ride": {
        "gain": -12,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "bass": {
        "gain": -4
      },
      "sub": {
        "gain": -12
      },
      "piano": {
        "gain": -4,
        "pan": -0.15,
        "send": {
          "reverb": 0.15
        }
      },
      "pad": {
        "gain": -13,
        "send": {
          "reverb": 0.3
        }
      },
      "square": {
        "gain": -0.9,
        "pan": 0.05,
        "send": {
          "delay": 0.08,
          "reverb": 0.15
        }
      },
      "bell": {
        "gain": -5.7,
        "pan": 0.25,
        "send": {
          "delay": 0.15,
          "reverb": 0.2
        }
      },
      "megaSaw": {
        "gain": -5.3,
        "pan": -0.1,
        "send": {
          "reverb": 0.15
        }
      },
      "arp": {
        "gain": -10,
        "pan": 0.25,
        "send": {
          "delay": 0.12,
          "reverb": 0.15
        }
      },
      "choir": {
        "gain": -10.2,
        "send": {
          "reverb": 0.5
        }
      },
      "third": {
        "gain": -7.1,
        "pan": 0.15,
        "send": {
          "reverb": 0.15
        }
      },
      "counter": {
        "gain": -6.3,
        "pan": -0.2,
        "send": {
          "delay": 0.12,
          "reverb": 0.15
        }
      }
    },
    "master": {
      "master": 0,
      "masterEffects": [
        {
          "id": "mbCompN",
          "params": {
            "lowFrequency": 180,
            "highFrequency": 1800,
            "low.threshold": -26,
            "low.ratio": 4,
            "low.attack": 0.06,
            "low.release": 0.22,
            "low.knee": 8,
            "mid.threshold": -22,
            "mid.ratio": 3.5,
            "mid.attack": 0.018,
            "mid.release": 0.08,
            "mid.knee": 12,
            "high.threshold": -26,
            "high.ratio": 2.5,
            "high.attack": 0.01,
            "high.release": 0.06,
            "high.knee": 10
          }
        },
        {
          "id": "gain",
          "params": {
            "gain": -5.8
          }
        }
      ],
      "fx": {
        "reverb": {
          "decay": 1.2
        }
      }
    },
    "pump": null,
    "exciter": null,
    "sectionFx": {
      "version": 1,
      "rules": [
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0.9895833333333334,
          "to": 1,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "Chorus",
          "sourceIndex": 2
        }
      ]
    }
  },
  "uk-garage": {
    "seed": "banger-seed-uk-garage",
    "at": "2026-10-09T12:10:30.460Z",
    "strips": {
      "hook": {
        "gain": -2,
        "pan": -0.05,
        "send": {
          "delay": 0.052,
          "reverb": 0.3
        }
      },
      "kick": {
        "eq": {
          "low": 1
        }
      },
      "snare": {
        "gain": -1,
        "send": {
          "reverb": 0.2
        }
      },
      "clap": {
        "gain": -2,
        "send": {
          "reverb": 0.25
        }
      },
      "hats": {
        "gain": -4.4,
        "pan": 0.2
      },
      "ohats": {
        "gain": -6,
        "pan": -0.2
      },
      "crash": {
        "gain": 3.84,
        "pan": 0.2,
        "send": {
          "reverb": 0.9
        },
        "eq": {
          "high": 2.7
        }
      },
      "fill": {
        "gain": -5,
        "pan": 0.2,
        "send": {
          "reverb": 0.3
        }
      },
      "shaker": {
        "gain": -14,
        "pan": -0.3
      },
      "tambourine": {
        "gain": -9.52,
        "pan": -0.3,
        "send": {
          "reverb": 0.15
        }
      },
      "cowbell": {
        "gain": -9.52,
        "pan": 0.323,
        "send": {
          "reverb": 0.869
        }
      },
      "congas": {
        "gain": -8,
        "pan": -0.2,
        "send": {
          "reverb": 0.15
        },
        "eq": {
          "low": -2.4
        }
      },
      "ride": {
        "gain": -12,
        "pan": 0.3,
        "send": {
          "reverb": 0.2
        }
      },
      "bass": {
        "gain": -2
      },
      "sub": {
        "gain": -12
      },
      "piano": {
        "gain": -5.4,
        "pan": -0.1,
        "send": {
          "delay": 0.021,
          "reverb": 0.3
        }
      },
      "pad": {
        "gain": -10,
        "send": {
          "reverb": 0.5
        },
        "eq": {
          "low": -5
        }
      },
      "square": {
        "gain": -1.1,
        "pan": 0.05,
        "send": {
          "delay": 0.1,
          "reverb": 0.2
        },
        "effects": [
          {
            "id": "peq",
            "params": {
              "f3": 3000,
              "g3": -2,
              "q3": 0.9
            }
          }
        ]
      },
      "bell": {
        "gain": -4.7,
        "pan": 0.2,
        "send": {
          "delay": 0.063,
          "reverb": 0.45
        }
      },
      "megaSaw": {
        "gain": -4.2,
        "send": {
          "reverb": 0.25
        },
        "eq": {
          "low": -3
        }
      },
      "arp": {
        "gain": -8.3,
        "pan": -0.25,
        "send": {
          "delay": 0.02,
          "reverb": 0.2
        },
        "effects": [
          {
            "id": "autopanner",
            "params": {
              "rateSync": 1,
              "rateDivision": 2,
              "depth": 0.5,
              "wet": 1
            }
          }
        ]
      },
      "choir": {
        "gain": -7,
        "send": {
          "reverb": 0.5
        },
        "effects": [
          {
            "id": "widener"
          }
        ]
      },
      "third": {
        "gain": -7,
        "pan": 0.15,
        "send": {
          "delay": 0.1,
          "reverb": 0.3
        }
      },
      "counter": {
        "gain": -6.6,
        "pan": 0.15,
        "send": {
          "delay": 0.073,
          "reverb": 0.4
        }
      }
    },
    "master": {
      "master": 0,
      "masterEffects": [
        {
          "id": "mbCompN",
          "params": {
            "lowFrequency": 180,
            "highFrequency": 1800,
            "low.threshold": -26,
            "low.ratio": 4,
            "low.attack": 0.06,
            "low.release": 0.22,
            "low.knee": 8,
            "mid.threshold": -22,
            "mid.ratio": 3.5,
            "mid.attack": 0.018,
            "mid.release": 0.08,
            "mid.knee": 12,
            "high.threshold": -26,
            "high.ratio": 2.5,
            "high.attack": 0.01,
            "high.release": 0.06,
            "high.knee": 10
          }
        },
        {
          "id": "gain",
          "params": {
            "gain": -5.8
          }
        }
      ],
      "fx": {
        "reverb": {
          "decay": 2.8
        }
      }
    },
    "pump": null,
    "exciter": null,
    "sectionFx": {
      "version": 1,
      "rules": [
        {
          "role": "hook",
          "section": "drop",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0.9895833333333334,
          "to": 1,
          "chain": [
            {
              "id": "delay",
              "params": {
                "sync": 1,
                "division": 0.75,
                "feedback": 0.6,
                "wet": 0.5
              }
            }
          ],
          "sourceSection": "Drop",
          "sourceIndex": 2
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build",
          "sourceIndex": 1
        },
        {
          "role": "bass",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build 2",
          "sourceIndex": 4
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build",
          "sourceIndex": 1
        },
        {
          "role": "sub",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build 2",
          "sourceIndex": 4
        },
        {
          "role": "piano",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build",
          "sourceIndex": 1
        },
        {
          "role": "piano",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build 2",
          "sourceIndex": 4
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build",
          "sourceIndex": 1
        },
        {
          "role": "pad",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build 2",
          "sourceIndex": 4
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build",
          "sourceIndex": 1
        },
        {
          "role": "square",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build 2",
          "sourceIndex": 4
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 0,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build",
          "sourceIndex": 1
        },
        {
          "role": "arp",
          "section": "build",
          "occurrence": 1,
          "occurrences": 2,
          "from": 0,
          "to": 1,
          "chain": [
            {
              "id": "filter",
              "params": {
                "type": "lowpass",
                "frequency": 350,
                "Q": 1.1,
                "sweep": 1,
                "sweepTo": 14000
              }
            }
          ],
          "sourceSection": "Build 2",
          "sourceIndex": 4
        }
      ]
    }
  }
};
