// MAKE A BANGER — each style's channels, as its seed banger has them. GENERATED by Use as
// Style (tools/lib/banger-seeds.js); do not edit by hand. A style with no entry here plays
// its recipe's own channels (tools/lib/banger/styles/<style>.js); one with an entry plays
// these over them, job by job:
//
//   strips   per job: fader, pan, EQ, sends, inserts, note FX — as the seed's channel had them
//   master   the master fader, its chain and the reverb/delay returns
//   pump     the chords' gate (the Sidechain Pump switch), taken off the chords channel
//   exciter  the hook's exciter (the moods that use one), taken off the hook channel
export const BANGER_CHANNELS = {};
