// MAKE A BANGER — Sound Combos: a style's sounds and channels saved under a name, from a
// banger somebody tuned on the desk (Save as Combo…). GENERATED by tools/lib/banger-seeds.js;
// do not edit by hand. Per style, per combo:
//
//   label     what the dialog calls it
//   sounds    { parts, kits: { style } } — over the style's own sounds (sounds.js)
//   channels  as channels.js holds them — over the style's own channels
//   refs      the banger's parts, which a combo's faders are matched against (levels.js)
//   from      the song it was saved from; made, when
export const BANGER_COMBOS = {};
