// World sprites: obstacles, pickups, portal, villain, props. Palette per sprite.

export const WORLD_SPRITES = {
  // -- obstacles ------------------------------------------------------------
  // Thorn cactus: warm red-orange so it pops against every cabinet's ground
  // (greens matched the plumber turf exactly and vanished into it). Only the
  // fallback for when the vector painters are unavailable — sprites/props.js
  // draws the version the game actually shows.
  cactus: {
    pal: { g: '#d84828', d: '#8a2018', w: '#f8d0a0' },
    grid: [
      '.....wggw.....',
      '.....gdgg.....',
      '.w...gdgg...w.',
      '.gw.wgdggw.wg.',
      '.gg..gdgg..gg.',
      '.gg..gdgg..gg.',
      'wggggggggggggw',
      '..ggwgdggwgg..',
      '.....gdgg.....',
      '....wgdggw....',
      '.....gdgg.....',
      '...dddddddd...',
    ],
  },
  cactusBig: {
    pal: { g: '#d84828', d: '#8a2018', w: '#f8d0a0' },
    grid: [
      '.......wggw.......',
      '.......gdgg.......',
      '..w....gdgg....w..',
      '..gw..wgdggw..wg..',
      '..gg...gdgg...gg..',
      '..gg...gdgg...gg..',
      '..gg...gdgg...gg..',
      'wgggggggdggggggggw',
      '...ggwggdggwgg....',
      '.......gdgg.......',
      '......wgdggw......',
      '.......gdgg.......',
      '.......gdgg.......',
      '....dddddddddd....',
    ],
  },
  crate: {
    pal: { w: '#c89858', d: '#8a6432', q: '#f6d33c', o: '#5a4020' },
    grid: [
      'oooooooooooo',
      'owwwwwwwwwdo',
      'owqqwwwqqwdo',
      'owqwwwwwqwdo',
      'owwwwqwwwwdo',
      'owwwwqwwwwdo',
      'owqwwwwwqwdo',
      'owqqwwwqqwdo',
      'owwwwwwwwwdo',
      'oddddddddddo',
      'oooooooooooo',
      '............',
    ],
  },
  barrel: {
    pal: { w: '#b07840', d: '#7a4c22', m: '#5a3818', h: '#d09858' },
    grid: [
      '....wwwwww....',
      '..wwddddddww..',
      '.wdwwwwwwwwdw.',
      '.wdwhwwwwhwdw.',
      'wdwwmwwwwmwwdw',
      'wdwhwwwwwwhwdw',
      'wdwwwwmmwwwwdw',
      'wdwhwwwwwwhwdw',
      'wdwwmwwwwmwwdw',
      '.wdwhwwwwhwdw.',
      '.wdwwwwwwwwdw.',
      '..wwddddddww..',
      '....wwwwww....',
    ],
  },
  drone: {
    pal: { m: '#8858c8', d: '#5a3890', e: '#f6d33c', w: '#c8b8e8' },
    grid: [
      '.ww......ww.',
      '..w.mmmm.w..',
      '..mmmddmm...',
      '.mmemmmmem..',
      '.mmmmmmmmm..',
      '..mmmddmm...',
      '...m....m...',
      '............',
    ],
  },
  buzzbird: {
    pal: { m: '#d87830', d: '#a85820', e: '#1a1028', w: '#f0a860' },
    grid: [
      '..ww........',
      '.wwww..mmm..',
      '..wwmmmmmm..',
      '...mmmmmem..',
      '..wwmmmmmm>.',
      '.wwww..mmm..',
      '..ww........',
      '............',
    ],
  },
  icicle: {
    pal: { i: '#b8e0f8', d: '#78b0e0', w: '#e8f8ff' },
    grid: [
      'iiiiiiii',
      'widiidiw',
      '.widiiw.',
      '.widiw..',
      '..wiw...',
      '..wiw...',
      '...w....',
      '...w....',
    ],
  },
  chair: { // rolling office chair
    pal: { s: '#3a3a48', w: '#6a6a7a', k: '#1a1a24' },
    grid: [
      '.ssssss.....',
      '.ssssss.....',
      '.sssssss....',
      '.sssssss....',
      '....w.......',
      '....w.......',
      '..wwwww.....',
      '.k..w..k....',
      'kk.....kk...',
      '............',
    ],
  },
  printer: {
    pal: { g: '#8a8a98', d: '#5a5a68', w: '#e8e8f0', r: '#d83030' },
    grid: [
      '..gggggggg..',
      '.gddddddddg.',
      '.gdwwwwwwdg.',
      'ggggggggggog'.replace('o', 'r'),
      'gddddddddddg',
      'gdwwwwwwwwdg',
      'gggggggggggg',
      '............',
    ],
  },
  tombstone: {
    pal: { g: '#8a8a98', d: '#5a5a68', m: '#3a9c48' },
    grid: [
      '...gggggg...',
      '..gggggggg..',
      '..gddddddg..',
      '..gdgggggg..',
      '..gggggggg..',
      '..gggggggg..',
      '.mgggggggm..',
      'mmmmmmmmmmm.',
    ],
  },
  cardboardMonster: {
    pal: { c: '#c8a068', d: '#9a7848', e: '#1a1028', t: '#e8e8f0' },
    grid: [
      '.cccccccccc.',
      'cctccccccdc.',
      'ccecccecccc.',
      'cccccccccdc.',
      'ccdcccccccc.',
      'cccc.ccccdc.',
      'ccccccccccc.',
      'ccd......dc.',
      'cc........c.',
      '............',
    ],
  },
  // -- pickups --------------------------------------------------------------
  coin: {
    pal: { g: '#f6d33c', d: '#c8a020', w: '#fff8d0' },
    grid: [
      '..gggg..',
      '.gwwddg.',
      'gwgggddg',
      'gwgggddg',
      'gwgggddg',
      'gwgggddg',
      '.gwwddg.',
      '..gggg..',
    ],
  },
  battery: {
    pal: { g: '#48c848', d: '#2a8a2a', w: '#d0ffd0', k: '#1a1a24' },
    grid: [
      '...kk...',
      '.kkkkkk.',
      '.kggggk.',
      '.kgwwgk.',
      '.kggggk.',
      '.kgddgk.',
      '.kkkkkk.',
      '........',
    ],
  },
  capShield: {
    pal: { b: '#4890f0', w: '#c8e0ff', k: '#1a1a24' },
    grid: [
      '..bbbb..',
      '.bwwbbb.',
      'bwbbbbbb',
      'bwbbbbbb',
      'bbbbbbbb',
      '.bbbbbb.',
      '..bbbb..',
      '........',
    ],
  },
  capMagnet: {
    pal: { r: '#e04848', w: '#f0f0f8', k: '#1a1a24' },
    grid: [
      '.rr..rr.',
      '.rr..rr.',
      '.rr..rr.',
      '.rrrrrr.',
      '..rrrr..',
      '.ww..ww.',
      '.ww..ww.',
      '........',
    ],
  },
  capStar: {
    pal: { g: '#f6d33c', w: '#fff8d0' },
    grid: [
      '...gg...',
      '...gg...',
      '.gggggg.',
      '..gggg..',
      '..gwwg..',
      '.gg..gg.',
      'g......g',
      '........',
    ],
  },
  capSlow: {
    pal: { c: '#48c8c8', w: '#e0ffff', k: '#1a1a24' },
    grid: [
      '..cccc..',
      '.cwwwwc.',
      'cwwkwwwc',
      'cwwkwwwc',
      'cwwkkwwc',
      'cwwwwwwc',
      '.cwwwwc.',
      '..cccc..',
    ],
  },
  appliance: { // the Highly Necessary Golden Appliance (a toaster)
    pal: { g: '#f6d33c', d: '#c8a020', w: '#fff8d0', k: '#5a4020' },
    grid: [
      '..k..k......',
      '.wwwwwwww...',
      'gwggggggwg..',
      'ggggddgggg..',
      'gggggggggg..',
      'ggddddddgg..',
      '.gggggggg...',
      '..k....k....',
    ],
  },
  portal: { // co-op cable portal ring
    pal: { c: '#48e0c8', d: '#28a090', w: '#d0fff8' },
    grid: [
      '..cccccc..',
      '.cwddddwc.',
      'cwd....dwc',
      'cd......dc',
      'cd......dc',
      'cd......dc',
      'cd......dc',
      'cwd....dwc',
      '.cwddddwc.',
      '..cccccc..',
    ],
  },
  fuse: {
    pal: { g: '#c8c8d8', d: '#8a8a98', r: '#e04848', w: '#fff' },
    grid: [
      '..gg..',
      '.grrg.',
      '.grrg.',
      '.gwwg.',
      '.grrg.',
      '..gg..',
    ],
  },
  boostPad: {
    pal: { y: '#f6d33c', o: '#e07820' },
    grid: [
      'o>........o>'.replace(/>/g, 'y'),
      'oyy.....oyy.',
      'oyyy...oyyy.',
      'oyy.....oyy.',
      'oy........oy'.replace(/\./g, '.'),
    ],
  },
  // -- villain --------------------------------------------------------------
  eggshell: { // Don K. Eggshell in clown-copter (24 wide)
    pal: { s: '#8a5a3a', d: '#6a4228', m: '#c83030', g: '#e8e8f0', h: '#48c848', c: '#f0f0f8', k: '#1a1a24', y: '#f6d33c', e: '#fff' },
    grid: [
      '.....kkkkkkkkkk.........',
      '..kkk..........kkk.....',
      '........ssssss..........',
      '.......ssssssss.........',
      '......ssgg..ggss........',
      '......ssgkggkgss........', // goggles
      '......ssssssssss........',
      '......smmmmmmmms........', // mustache
      '.....ssmmmmmmmmss.......',
      '.....sssssssssss........',
      '....hshhhhhhhhsh........', // spiky shell peeking
      '...hhsshhhhhhsshh.......',
      '....cccccccccccc........',
      '...cyccccccccccyc.......', // copter bucket
      '...ccccccccccccc........',
      '....ccc.....ccc.........',
    ],
  },
  dustdevil: { // DUST DEVIL 9000 vacuum
    pal: { r: '#c83030', d: '#8a2020', g: '#8a8a98', k: '#1a1a24', w: '#fff', e: '#48c8f0' },
    grid: [
      '....kk......',
      '....kk......',
      '...rrrr.....',
      '..rrrrrr....',
      '..rerrer....', // little LED "eyes"
      '..rrrrrr....',
      '..rddddr....',
      '..rrrrrr....',
      '.ggggggggg..',
      '.kk.....kk..',
    ],
  },
  goldTrophy: {
    pal: { g: '#f6d33c', d: '#c8a020', w: '#fff8d0' },
    grid: [
      'gggggggg',
      '.gwwwwg.',
      '.gwwwwg.',
      '..gwwg..',
      '...gg...',
      '...gg...',
      '..gggg..',
      '.gggggg.',
    ],
  },
};
