/*
 * GENERATED by work/local/robot_voice_export.py --into src/engine/jmjr4/data.js
 * from robot_voice.py — do not edit. Every phoneme, voice, tract constant and level
 * table JMJR-4 reads. Change the Python tables and re-export; tests/jmjr4-data.js
 * checks the two agree whenever the Python export is present.
 */
export const JMJR4_DATA = {
 "block": 64,
 "levels": {
  "asp": 0.35,
  "bar": 0.4,
  "no_vowel_ref": 0.0707,
  "peak_ceiling": 0.95,
  "release_asp": 0.32,
  "release_asp_tail": 0.09,
  "target_rms_dbfs": -20.0
 },
 "live": {
  "asp_rms_unit": 0.04953809,
  "asp_rms_unit_after_stop": {
   "B": 0.00814498,
   "CH": 0.02247883,
   "D": 0.01233906,
   "G": 0.01746424,
   "JH": 0.02130707,
   "K": 0.02257304,
   "P": 0.01184468,
   "T": 0.01377508
  },
  "asp_rms_unit_by_vowel": {
   "AA": 0.08489947,
   "AE": 0.06589149,
   "AH": 0.09290494,
   "AW": 0.07814403,
   "AX": 0.04953809,
   "AY": 0.07961005,
   "EH": 0.05572926,
   "ER": 0.06291802,
   "EY": 0.05160303,
   "IH": 0.0447911,
   "IY": 0.03815211,
   "L": 0.04953809,
   "M": 0.05031673,
   "N": 0.04888335,
   "NG": 0.04776711,
   "OH": 0.04576225,
   "OO": 0.03396535,
   "OU": 0.04576225,
   "OW": 0.08489947,
   "OY": 0.04684223,
   "R": 0.04953809,
   "UH": 0.06659855,
   "UU": 0.0453822,
   "W": 0.04953809,
   "Y": 0.04953809
  },
  "at_hz": 130,
  "bar_rms_unit": 0.09910528,
  "noise": {
   "B": {
    "length": 529,
    "rms_unit": 0.1100066
   },
   "CH": {
    "length": 4057,
    "rms_unit": 0.12376685
   },
   "D": {
    "length": 529,
    "rms_unit": 0.22115623
   },
   "DH": {
    "length": 2205,
    "rms_unit": 0.22029705
   },
   "F": {
    "length": 3969,
    "rms_unit": 0.48502813
   },
   "G": {
    "length": 661,
    "rms_unit": 0.13377083
   },
   "JH": {
    "length": 2646,
    "rms_unit": 0.12154377
   },
   "K": {
    "length": 1102,
    "rms_unit": 0.12389551
   },
   "P": {
    "length": 882,
    "rms_unit": 0.10755977
   },
   "S": {
    "length": 4410,
    "rms_unit": 0.26954241
   },
   "SH": {
    "length": 4851,
    "rms_unit": 0.27653972
   },
   "T": {
    "length": 882,
    "rms_unit": 0.19082174
   },
   "TH": {
    "length": 3969,
    "rms_unit": 0.52153997
   },
   "V": {
    "length": 2646,
    "rms_unit": 0.23273865
   },
   "Z": {
    "length": 3087,
    "rms_unit": 0.12432028
   },
   "ZH": {
    "length": 3528,
    "rms_unit": 0.13292425
   }
  },
  "vref_by_vowel": {
   "AA": 0.09166374,
   "AE": 0.08309569,
   "AH": 0.0904753,
   "AW": 0.09514976,
   "AX": 0.08241441,
   "AY": 0.08212022,
   "EH": 0.08071824,
   "ER": 0.08076064,
   "EY": 0.07844203,
   "IH": 0.07888103,
   "IY": 0.08707097,
   "L": 0.04987396,
   "M": 0.0707,
   "N": 0.0707,
   "NG": 0.0707,
   "OH": 0.08337457,
   "OO": 0.0896461,
   "OU": 0.08687463,
   "OW": 0.09138617,
   "OY": 0.0820298,
   "R": 0.0501329,
   "UH": 0.08262099,
   "UU": 0.08219464,
   "W": 0.05413925,
   "Y": 0.05259833
  }
 },
 "phonemes": {
  "AA": {
   "f": [
    700,
    1100,
    2500
   ],
   "k": "V"
  },
  "AE": {
   "f": [
    650,
    1650,
    2450
   ],
   "k": "V"
  },
  "AH": {
   "f": [
    750,
    1200,
    2500
   ],
   "k": "V"
  },
  "AW": {
   "f": [
    600,
    950,
    2450
   ],
   "k": "V"
  },
  "AX": {
   "f": [
    500,
    1400,
    2500
   ],
   "k": "V"
  },
  "AY": {
   "f": [
    [
     700,
     1200,
     2500
    ],
    [
     350,
     2100,
     2700
    ]
   ],
   "k": "V"
  },
  "B": {
   "burst": 0.012,
   "c": 900,
   "g": 0.075,
   "k": "S",
   "locus": [
    200,
    700,
    2300
   ],
   "q": 1.5,
   "voiced": true,
   "vot": 0.008
  },
  "CH": {
   "burst": 0.1,
   "c": 3500,
   "g": 0.13,
   "k": "S",
   "locus": [
    200,
    2000,
    2600
   ],
   "q": 2.0,
   "vot": 0.02
  },
  "D": {
   "burst": 0.012,
   "c": 4000,
   "g": 0.075,
   "k": "S",
   "locus": [
    200,
    1800,
    2600
   ],
   "q": 1.5,
   "voiced": true,
   "vot": 0.008
  },
  "DH": {
   "g": 0.16,
   "k": "F",
   "locus": [
    200,
    1600,
    2600
   ],
   "spec": [
    [
     5500,
     0.7,
     0.7
    ],
    [
     8000,
     1.0,
     0.4
    ]
   ],
   "voiced": true
  },
  "EH": {
   "f": [
    550,
    1700,
    2500
   ],
   "k": "V"
  },
  "ER": {
   "f": [
    490,
    1350,
    1690
   ],
   "k": "V"
  },
  "EY": {
   "f": [
    [
     500,
     1900,
     2600
    ],
    [
     350,
     2200,
     2800
    ]
   ],
   "k": "V"
  },
  "F": {
   "g": 0.12,
   "k": "F",
   "locus": [
    200,
    1000,
    2400
   ],
   "spec": [
    [
     3500,
     0.5,
     0.6
    ],
    [
     7000,
     0.7,
     0.6
    ]
   ]
  },
  "G": {
   "burst": 0.015,
   "c": 2000,
   "g": 0.075,
   "k": "S",
   "locus": [
    200,
    2200,
    2500
   ],
   "q": 1.5,
   "voiced": true,
   "vot": 0.01
  },
  "H": {
   "k": "H"
  },
  "IH": {
   "f": [
    420,
    1900,
    2600
   ],
   "k": "V"
  },
  "IY": {
   "f": [
    300,
    2200,
    2900
   ],
   "k": "V"
  },
  "JH": {
   "burst": 0.06,
   "c": 3000,
   "g": 0.09,
   "k": "S",
   "locus": [
    200,
    2000,
    2600
   ],
   "q": 2.0,
   "voiced": true,
   "vot": 0.01
  },
  "K": {
   "burst": 0.025,
   "c": 2000,
   "g": 0.11,
   "k": "S",
   "locus": [
    200,
    2200,
    2500
   ],
   "q": 1.5,
   "vot": 0.06
  },
  "L": {
   "amp": 0.6,
   "f": [
    360,
    1100,
    2600
   ],
   "k": "V"
  },
  "M": {
   "amp": 0.22,
   "f": [
    320,
    1150,
    2050
   ],
   "k": "V",
   "nasal": true,
   "nz": 750.0
  },
  "N": {
   "amp": 0.22,
   "f": [
    320,
    1250,
    2200
   ],
   "k": "V",
   "nasal": true,
   "nz": 1550.0
  },
  "NG": {
   "amp": 0.22,
   "f": [
    280,
    1300,
    2500
   ],
   "k": "V",
   "nasal": true,
   "nz": 3000.0
  },
  "OH": {
   "f": [
    450,
    950,
    2400
   ],
   "k": "V"
  },
  "OO": {
   "f": [
    320,
    800,
    2300
   ],
   "k": "V"
  },
  "OU": {
   "f": [
    [
     450,
     950,
     2400
    ],
    [
     350,
     800,
     2300
    ]
   ],
   "k": "V"
  },
  "OW": {
   "f": [
    [
     700,
     1100,
     2500
    ],
    [
     320,
     800,
     2300
    ]
   ],
   "k": "V"
  },
  "OY": {
   "f": [
    [
     450,
     900,
     2400
    ],
    [
     350,
     2000,
     2700
    ]
   ],
   "k": "V"
  },
  "P": {
   "burst": 0.02,
   "c": 900,
   "g": 0.11,
   "k": "S",
   "locus": [
    200,
    700,
    2300
   ],
   "q": 1.5,
   "vot": 0.04
  },
  "Q": {
   "k": "_"
  },
  "R": {
   "amp": 0.6,
   "f": [
    420,
    1150,
    1600
   ],
   "k": "V"
  },
  "S": {
   "g": 0.2,
   "k": "F",
   "locus": [
    200,
    1800,
    2600
   ],
   "spec": [
    [
     7200,
     4.0,
     1.0
    ],
    [
     5400,
     5.0,
     0.45
    ]
   ]
  },
  "SH": {
   "g": 0.23,
   "k": "F",
   "locus": [
    200,
    2000,
    2600
   ],
   "spec": [
    [
     2800,
     2.5,
     1.0
    ],
    [
     4200,
     3.0,
     0.55
    ]
   ]
  },
  "T": {
   "burst": 0.02,
   "c": 4000,
   "g": 0.11,
   "k": "S",
   "locus": [
    200,
    1800,
    2600
   ],
   "q": 1.5,
   "vot": 0.05
  },
  "TH": {
   "g": 0.12,
   "k": "F",
   "locus": [
    200,
    1800,
    2600
   ],
   "spec": [
    [
     6000,
     0.6,
     0.7
    ],
    [
     8500,
     1.0,
     0.5
    ]
   ]
  },
  "UH": {
   "f": [
    600,
    1200,
    2400
   ],
   "k": "V"
  },
  "UU": {
   "f": [
    440,
    1020,
    2240
   ],
   "k": "V"
  },
  "V": {
   "g": 0.18,
   "k": "F",
   "locus": [
    200,
    1000,
    2400
   ],
   "spec": [
    [
     3500,
     0.5,
     0.6
    ],
    [
     7000,
     0.7,
     0.6
    ]
   ],
   "voiced": true
  },
  "W": {
   "amp": 0.6,
   "f": [
    320,
    800,
    2300
   ],
   "k": "V"
  },
  "Y": {
   "amp": 0.6,
   "f": [
    300,
    2200,
    2900
   ],
   "k": "V"
  },
  "Z": {
   "g": 0.13,
   "k": "F",
   "locus": [
    200,
    1800,
    2600
   ],
   "spec": [
    [
     7200,
     4.0,
     1.0
    ],
    [
     5400,
     5.0,
     0.45
    ]
   ],
   "voiced": true
  },
  "ZH": {
   "g": 0.3,
   "k": "F",
   "locus": [
    200,
    2000,
    2600
   ],
   "spec": [
    [
     2800,
     2.5,
     1.0
    ],
    [
     4200,
     3.0,
     0.55
    ]
   ],
   "voiced": true
  },
  "_": {
   "k": "_"
  },
  "|": {
   "dip": 0.55,
   "k": "B"
  }
 },
 "sample_rate": 44100,
 "schema": "robot-voice-data/1",
 "seg": {
  "glides": [
   "W",
   "Y"
  ],
  "liquids": [
   "L",
   "R"
  ],
  "nasalise": 0.04,
  "sonorants": [
   "L",
   "M",
   "N",
   "NG",
   "R",
   "W",
   "Y"
  ],
  "tr": 0.06
 },
 "source": {
  "radiation": 0.97,
  "skew": 0.7,
  "tilt_ref_hz": 3000.0
 },
 "text": {
  "apostrophes": "\u2019\u02bc\u00b4`",
  "arpa": {
   "AA": "AH",
   "AE": "AE",
   "AH": "UH",
   "AO": "AW",
   "AW": "OW",
   "AY": "AY",
   "B": "B",
   "CH": "CH",
   "D": "D",
   "DH": "DH",
   "EH": "EH",
   "ER": "ER",
   "EY": "EY",
   "F": "F",
   "G": "G",
   "HH": "H",
   "IH": "IH",
   "IY": "IY",
   "JH": "JH",
   "K": "K",
   "L": "L",
   "M": "M",
   "N": "N",
   "NG": "NG",
   "OW": "OU",
   "OY": "OY",
   "P": "P",
   "R": "R",
   "S": "S",
   "SH": "SH",
   "T": "T",
   "TH": "TH",
   "UH": "UU",
   "UW": "OO",
   "V": "V",
   "W": "W",
   "Y": "Y",
   "Z": "Z",
   "ZH": "ZH"
  },
  "dict_url": "https://raw.githubusercontent.com/cmusphinx/cmudict/master/cmudict.dict",
  "function_words": [
   "a",
   "about",
   "am",
   "an",
   "and",
   "are",
   "as",
   "at",
   "be",
   "been",
   "but",
   "by",
   "can",
   "could",
   "did",
   "do",
   "does",
   "down",
   "for",
   "from",
   "had",
   "has",
   "have",
   "he",
   "her",
   "him",
   "his",
   "i",
   "if",
   "in",
   "into",
   "is",
   "it",
   "its",
   "may",
   "me",
   "might",
   "must",
   "my",
   "no",
   "not",
   "of",
   "off",
   "on",
   "onto",
   "or",
   "our",
   "out",
   "over",
   "shall",
   "she",
   "should",
   "so",
   "than",
   "that",
   "the",
   "their",
   "them",
   "then",
   "these",
   "they",
   "this",
   "those",
   "to",
   "up",
   "us",
   "was",
   "we",
   "were",
   "will",
   "with",
   "would",
   "you",
   "your"
  ],
  "hold_max": 6.0,
  "hold_per_letter": 0.55,
  "l2s": [
   [
    "tch",
    "CH"
   ],
   [
    "igh",
    "AY1"
   ],
   [
    "ough",
    "AH1 F"
   ],
   [
    "ch",
    "CH"
   ],
   [
    "sh",
    "SH"
   ],
   [
    "th",
    "TH"
   ],
   [
    "ph",
    "F"
   ],
   [
    "ng",
    "NG"
   ],
   [
    "ck",
    "K"
   ],
   [
    "qu",
    "K W"
   ],
   [
    "ee",
    "IY1"
   ],
   [
    "ea",
    "IY1"
   ],
   [
    "oo",
    "UW1"
   ],
   [
    "ou",
    "AW1"
   ],
   [
    "ow",
    "OW1"
   ],
   [
    "ay",
    "EY1"
   ],
   [
    "ai",
    "EY1"
   ],
   [
    "ey",
    "EY1"
   ],
   [
    "oy",
    "OY1"
   ],
   [
    "oi",
    "OY1"
   ],
   [
    "ie",
    "IY1"
   ],
   [
    "a",
    "AE1"
   ],
   [
    "e",
    "EH1"
   ],
   [
    "i",
    "IH1"
   ],
   [
    "o",
    "AA1"
   ],
   [
    "u",
    "AH1"
   ],
   [
    "y",
    "IY0"
   ],
   [
    "b",
    "B"
   ],
   [
    "c",
    "K"
   ],
   [
    "d",
    "D"
   ],
   [
    "f",
    "F"
   ],
   [
    "g",
    "G"
   ],
   [
    "h",
    "HH"
   ],
   [
    "j",
    "JH"
   ],
   [
    "k",
    "K"
   ],
   [
    "l",
    "L"
   ],
   [
    "m",
    "M"
   ],
   [
    "n",
    "N"
   ],
   [
    "p",
    "P"
   ],
   [
    "r",
    "R"
   ],
   [
    "s",
    "S"
   ],
   [
    "t",
    "T"
   ],
   [
    "v",
    "V"
   ],
   [
    "w",
    "W"
   ],
   [
    "x",
    "K S"
   ],
   [
    "z",
    "Z"
   ]
  ],
  "ones": [
   "zero",
   "one",
   "two",
   "three",
   "four",
   "five",
   "six",
   "seven",
   "eight",
   "nine",
   "ten",
   "eleven",
   "twelve",
   "thirteen",
   "fourteen",
   "fifteen",
   "sixteen",
   "seventeen",
   "eighteen",
   "nineteen"
  ],
  "overrides": {
   "b33p": "B IY1 TH ER1 D IY0 TH R IY1 P IY1",
   "blastbot": "B L AE1 S T B AA0 T",
   "craigy": "K R EY1 G IY0",
   "cyan": "S AY1 AE0 N",
   "eggshell": "EH1 G SH EH2 L",
   "fernwick": "F ER1 N W IH0 K",
   "grumpos": "G R AH1 M P OW0 S",
   "kiko": "K IY1 K OW0",
   "mashenstein": "M AE1 SH AH0 N S T AY0 N",
   "mochi": "M OW1 CH IY0",
   "needlemouse": "N IY1 D AH0 L M AW2 S",
   "poyo": "P OY1 OW0",
   "raymn": "R EY1 M AH0 N",
   "thyme": "T AY1 M",
   "unpluggening": "AH0 N P L AH1 G AH0 N IH0 NG"
  },
  "prosody": {
   "accent_st": {
    "1": 2.5,
    "2": 1.0
   },
   "continuation_st": 1.5,
   "exclaim_st": -5.0,
   "first_accent_bonus": 1.2,
   "question_st": 6.0
  },
  "speed_max": 2.5,
  "speed_min": 0.4,
  "tens": [
   "",
   "",
   "twenty",
   "thirty",
   "forty",
   "fifty",
   "sixty",
   "seventy",
   "eighty",
   "ninety"
  ],
  "vowels": [
   "AA",
   "AE",
   "AH",
   "AO",
   "AW",
   "AY",
   "EH",
   "ER",
   "EY",
   "IH",
   "IY",
   "OW",
   "OY",
   "UH",
   "UW"
  ]
 },
 "timing": {
  "dur": {
   "AX": 0.07,
   "AY": 0.19,
   "B": 0.06,
   "CH": 0.11,
   "D": 0.06,
   "DH": 0.05,
   "ER": 0.13,
   "EY": 0.18,
   "F": 0.09,
   "G": 0.06,
   "H": 0.06,
   "JH": 0.1,
   "K": 0.08,
   "L": 0.07,
   "M": 0.07,
   "N": 0.07,
   "NG": 0.08,
   "OU": 0.18,
   "OW": 0.19,
   "OY": 0.19,
   "P": 0.08,
   "R": 0.07,
   "S": 0.1,
   "SH": 0.11,
   "T": 0.08,
   "TH": 0.09,
   "V": 0.06,
   "W": 0.06,
   "Y": 0.06,
   "Z": 0.07,
   "ZH": 0.08
  },
  "min_burst": 0.005,
  "min_closure": 0.018,
  "onset_burst": 1.7,
  "pause": {
   "!": 0.3,
   ".": 0.32,
   "?": 0.32,
   "clause": 0.18
  },
  "tr_pair": {
   "B": 0.03,
   "F": 0.025,
   "G": 0.045,
   "H": 0.015,
   "N": 0.025,
   "S": 0.02,
   "V": 0.04,
   "_": 0.02
  },
  "voice_lead": 0.012,
  "word_gap": 0.03
 },
 "tract": {
  "bw": [
   100.0,
   140.0,
   200.0,
   250.0
  ],
  "f4": 3400.0,
  "f5": [
   4500.0,
   300.0
  ],
  "gains": [
   1.0,
   1.0,
   0.35,
   0.15
  ],
  "hybrid_dep_exp": 0.187,
  "hybrid_f5_gain": 0.1,
  "hybrid_high_gain": 1.2589,
  "nasal_buzz_db": 22.0,
  "nasal_buzz_hz": 400.0,
  "nasal_high": 0.15,
  "nasal_high_max": 1.4,
  "nasal_pole": [
   250.0,
   2600.0
  ],
  "nasal_zero_bw": 90.0,
  "nasalise": 0.04,
  "tract_ref_gain": {
   "cascade": 0.13300109730935825,
   "parallel": 1.0
  }
 },
 "voice_gains": {
  "announcer": 1.4141319719366683,
  "chorister": 1.479197221645997,
  "dolores": 1.3529191264072666,
  "eggshell": 1.5025324358595318,
  "elder": 1.3610228162509124,
  "nasal": 1.3628718335038488,
  "robot": 0.9251186100062382,
  "small": 1.3752311133244979,
  "titan": 1.472765033606953
 },
 "voices": {
  "announcer": {
   "decl_st": -3.0,
   "f0": 118,
   "final_st": -4.0,
   "fscale": 1.0,
   "jitter": 0.0,
   "oq": 0.5,
   "range": 1.0,
   "release": 1.0,
   "speed": 1.0,
   "src": "glottal",
   "step_st": 0.0,
   "tilt": 0.0
  },
  "chorister": {
   "decl_st": -2.0,
   "f0": 146,
   "final_st": -3.0,
   "flutter": 0.35,
   "fscale": 1.04,
   "jitter": 0.05,
   "nasal": 0,
   "oq": 0.6,
   "range": 0.9,
   "release": 1.4,
   "res": 28,
   "speed": 0.95,
   "src": "glottal",
   "step_st": 0.0,
   "tilt": 3.0
  },
  "dolores": {
   "decl_st": -2.0,
   "f0": 124,
   "final_st": -6.0,
   "fscale": 1.0,
   "jitter": 0.0,
   "oq": 0.5,
   "range": 0.35,
   "release": 0.7,
   "speed": 1.12,
   "src": "glottal",
   "step_st": 0.0,
   "tilt": 0.0
  },
  "eggshell": {
   "decl_st": -4.0,
   "f0": 94,
   "final_st": -6.0,
   "fscale": 0.88,
   "jitter": 0.0,
   "oq": 0.42,
   "range": 0.9,
   "release": 1.2,
   "speed": 0.88,
   "src": "glottal",
   "step_st": 0.0,
   "tilt": 2.0
  },
  "elder": {
   "decl_st": -3.0,
   "f0": 168,
   "final_st": -5.0,
   "flutter": 1.3,
   "fscale": 1.08,
   "jitter": 0.35,
   "nasal": 18,
   "oq": 0.62,
   "range": 1.1,
   "release": 1.1,
   "res": 40,
   "speed": 0.9,
   "src": "glottal",
   "step_st": 0.0,
   "tilt": 5.0
  },
  "nasal": {
   "decl_st": -3.0,
   "f0": 132,
   "final_st": -4.0,
   "flutter": 0.2,
   "fscale": 1.02,
   "jitter": 0.0,
   "nasal": 62,
   "oq": 0.52,
   "range": 1.0,
   "release": 1.0,
   "res": 55,
   "speed": 1.0,
   "src": "glottal",
   "step_st": 0.0,
   "tilt": 1.0
  },
  "robot": {
   "decl_st": -2.0,
   "f0": 120,
   "final_st": -3.0,
   "fscale": 1.0,
   "jitter": 0.0,
   "oq": 0.5,
   "range": 0.6,
   "release": 1.3,
   "speed": 1.0,
   "src": "saw",
   "step_st": 2.0,
   "tilt": 0.0
  },
  "small": {
   "decl_st": -3.0,
   "f0": 178,
   "final_st": -4.0,
   "fscale": 1.16,
   "jitter": 0.0,
   "oq": 0.55,
   "range": 1.3,
   "release": 1.0,
   "speed": 1.05,
   "src": "glottal",
   "step_st": 0.0,
   "tilt": -1.0
  },
  "titan": {
   "decl_st": -3.0,
   "f0": 68,
   "final_st": -5.0,
   "flutter": 0.15,
   "fscale": 0.76,
   "jitter": 0.0,
   "nasal": 0,
   "oq": 0.44,
   "range": 0.7,
   "release": 1.5,
   "res": 72,
   "speed": 0.82,
   "src": "glottal",
   "step_st": 0.0,
   "tilt": 1.0
  }
 }
};
